# Generated by Django 4.2.7 on 2023-11-20 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='books_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.books'),
        ),
    ]
